[[language]]
name = "java"
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml", "build.gradle"]
language-server = { command = "java", args = [  
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=ALL",
    "-Xms1g",
    "--add-modules=ALL-SYSTEM",
    "--add-opens",
    "java.base/java.util=ALL-UNNAMED",
    "--add-opens",
    "java.base/java.lang=ALL-UNNAMED",
    "-javaagent:/home/epsku/.local/bin/lombok.jar",
    "-jar",
    "/home/epsku/.local/bin/jdtls/plugins/org.eclipse.equinox.app_1.6.200.v20220720-2012.jar",
    "-configuration",
    "/home/epsku/.local/bin/jdtls/config_linux",
    "-data",
    "/home/epsku/.cache/nvim/workspace"
] }
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "java"
source = { git = "https://github.com/tree-sitter/tree-sitter-java", rev = "bd6186c24d5eb13b4623efac9d944dcc095c0dad" }
